name: cardinal-ai-multimodel-app
base: core22
version: '1.128.1450'
summary: CardinalAI MultiModel App
description: |
  Aplicación de escritorio para interactuar con múltiples modelos de IA de CardinalAI.

grade: stable
confinement: strict

apps:
  cardinal-ai-multimodel-app:
    command: electron-launch $SNAP/src/main.js
    plugs:
      - network
      - desktop
      - wayland
      - x11
      - home
      - audio-playback
      - opengl

parts:
  cardinal-ai-multimodel:
    plugin: nodejs
    source: .
    nodejs-version: 18
    stage-packages:
      - libnss3
      - libxss1
      - libgtk-3-0
      - libasound2
